### ISSUE TITLE
Inexact wording in Quiz M4.03 Q1

### ISSUE THREAD

**Issue by ArturoAmorQ** [INRIA/scikit-learn-mooc#590]
As mentioned in [this forum post](https://mooc-forums.inria.fr/moocsl/t/question-1/7926), both answers are valid depending on how we set the `PolynomialFeatures` parameters.

**Comment by ogrisel** [comment]
@lfarhi @MarieCollin I merged #591 with the new wording. I let you propagate the change on the Fun platform. Since it only changes the phrasing of a question I think we can do this change in the current session.

**Comment by lesteve** [comment]
@lfarhi @MarieCollin actually we think there is a better wording for this question you may want to wait before changing it in FUN

**Comment by lfarhi** [comment]
I corrected the question in FUN, you can close

**Comment by lesteve** [comment]
:thinking: miscommunication we are still not happy about the wording (as I tried to say in my previous message)

Wait first until https://gitlab.inria.fr/learninglab/mooc-scikit-learn/mooc-scikit-learn-coordination/-/merge_requests/65 is merged (soon), and then this would be great if you could propagate the change in FUN. Sorry for the duplicated work ...

**Comment by ArturoAmorQ** [comment]
Thanks @lfarhi! Sorry to bother you again but you corrected the question using #591 and the correct wording is in #592

**Comment by lfarhi** [comment]
Sorry, as https://gitlab.inria.fr/learninglab/mooc-scikit-learn/mooc-scikit-learn-coordination/-/merge_requests/64 has been merged, I deduced that it was good !

**Comment by ArturoAmorQ** [comment]
Don't worry @lfarhi, it is good for now (no need to undo the change), but it can be improved!

**Comment by ogrisel** [comment]
I merged the new version. Let's close this issue once fun is updated again. Sorry @lfarhi  :)

**Comment by ArturoAmorQ** [comment]
This aws done in FUN. I am closing the issue. Thanks @lfarhi @MarieCollin !
